// apps/app/src/onboarding/pairing.mjs
//
// v1.2 Phase 09 — pairing-code lifecycle for Standout-style onboarding.
//
//   1. Student lands on /onboard/qr after LinkedIn OAuth.
//   2. Server generates a code via generatePairingCode(studentId) and
//      stores it in `pairing_sessions` (migration 0008).
//   3. Code is encoded into an sms:// URI ("sms:+14063210019&body=START-AB12CD")
//      and rendered as a QR (desktop) or a button (mobile).
//   4. Student texts the code from their iPhone; the Mac bridge forwards the
//      iMessage to /webhooks/mac-bridge.
//   5. The webhook calls parsePairingCode() on the body; if it matches, it
//      calls claimPairingCode(code, phone) which atomically:
//         - SELECT ... FOR UPDATE the pairing_sessions row
//         - Reject if claimed_at IS NOT NULL or expires_at < now()
//         - UPDATE claimed_at = now(), claimed_phone = phone
//         - UPDATE students.channel_address = phone when that LinkedIn
//           profile has no confirmed phone yet
//   6. Returns the studentId so the webhook handler can fire the
//      FIRST-CONTACT workflow with LinkedIn context.
//
// Code format: `START-` prefix + 6 chars from a 32-char alphabet that
// excludes the visually ambiguous I/L/0/1/O. 6 chars × 32 alphabet =
// ~1 billion codes, plenty given 24h TTL + claim-once + ~hundreds of
// students/day. Reading the code aloud or typing it on an iPhone keyboard
// is the main UX constraint.
//
// The `pairing_sessions` table is keyed by code (text PK) — no UUID
// surrogate. Codes are unique-by-construction; PK on text is fine at our
// scale and lets the claim path do a single index lookup.

import { randomInt } from "node:crypto";
import { hasLinkedInProfileUrl } from "../store.mjs";

// Visually distinct alphabet — drops I, L, O, 0, 1.
const CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
const CODE_LENGTH = 6;
const CODE_PREFIX = "START-";

// Loose-but-bounded regex for inbound parsing. Accepts START-{6..8} chars
// from A-Z 0-9 so codes generated by other modules in the future (e.g.
// a 7- or 8-char variant for ops-assist) parse without a code change.
const CODE_REGEX = /\bSTART-[A-Z0-9]{6,8}\b/;

/**
 * Generate a new pairing code, insert into pairing_sessions, return the code.
 *
 * @param {import('pg').Pool} pool   Postgres pool.
 * @param {string} studentId         Student to bind on claim.
 * @param {object} [opts]
 * @param {number} [opts.ttlHours=24]
 * @param {'qr'|'mobile-deeplink'|'manual'} [opts.source='qr']
 * @returns {Promise<string>}  The generated code (e.g. 'START-AB12CD').
 */
export async function generatePairingCode(pool, studentId, opts = {}) {
  if (!pool) throw new Error("generatePairingCode: pool is required");
  if (!studentId) throw new Error("generatePairingCode: studentId is required");
  await assertStudentPairingEligible(pool, studentId);

  const ttlHours = Number.isFinite(opts.ttlHours) ? opts.ttlHours : 24;
  const source = opts.source || "qr";

  // Collision handling: PK on `code` means an INSERT can in theory fail with
  // 23505 if two students happen to land on the same random code. With a
  // ~1B-code space, the birthday-bound probability is negligible at our
  // scale (hundreds/day) but we still retry on 23505 a few times to keep
  // the path defensively bulletproof.
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const code = CODE_PREFIX + randomChars(CODE_LENGTH);
    try {
      await pool.query(
        `insert into pairing_sessions (code, student_id, expires_at, source)
         values ($1, $2, now() + ($3 || ' hours')::interval, $4)`,
        [code, studentId, String(ttlHours), source],
      );
      return code;
    } catch (err) {
      if (err?.code !== "23505") throw err;
      // 23505 = unique_violation; retry with a new code.
    }
  }
  throw new Error("pairing_code_collision_after_retries");
}

/**
 * Parse a pairing code from an inbound message body.
 *
 * @param {string} text  Inbound iMessage / SMS body.
 * @returns {string | null}  The matched code (uppercased) or null.
 */
export function parsePairingCode(text) {
  if (!text || typeof text !== "string") return null;
  const m = text.toUpperCase().match(CODE_REGEX);
  return m ? m[0] : null;
}

/**
 * Atomically claim a pairing code for a phone.
 *
 * Rules:
 *   - Row must exist and not be expired.
 *   - Row must not already be claimed (claimed_at IS NULL).
 *   - On success: set claimed_at + claimed_phone AND bind students.channel_address
 *     to the phone only if this LinkedIn profile does not already have one.
 *
 * @param {import('pg').Pool} pool
 * @param {string} code   The full pairing code (e.g. 'START-AB12CD').
 * @param {string} phone  The phone that sent the iMessage.
 * @param {object} [opts]
 * @param {string} [opts.channelType='imessage']  Recorded on the student row.
 * @returns {Promise<{ok: true, studentId: string} | {ok: false, reason: string}>}
 */
export async function claimPairingCode(pool, code, phone, opts = {}) {
  if (!pool) throw new Error("claimPairingCode: pool is required");
  if (!code || !phone) return { ok: false, reason: "missing_args" };

  const channelType = opts.channelType || "imessage";
  const client = await pool.connect();
  try {
    await client.query("begin");

    const { rows } = await client.query(
      `select code, student_id, expires_at, claimed_at
         from pairing_sessions
        where code = $1
        for update`,
      [code],
    );
    const row = rows[0];

    if (!row) {
      await client.query("rollback");
      return { ok: false, reason: "code_not_found" };
    }
    if (row.claimed_at) {
      await client.query("rollback");
      return { ok: false, reason: "code_already_claimed" };
    }
    if (new Date(row.expires_at).getTime() < Date.now()) {
      await client.query("rollback");
      return { ok: false, reason: "code_expired" };
    }

    const studentResult = await client.query(
      `select id, linkedin_profile_url, channel_address, channel_confirmed_at
         from students
        where id = $1
        for update`,
      [row.student_id],
    );
    const student = studentResult.rows[0];
    if (!student) {
      await client.query("rollback");
      return { ok: false, reason: "student_not_found" };
    }
    if (!hasLinkedInProfileUrl(student.linkedin_profile_url)) {
      await client.query("rollback");
      return { ok: false, reason: "linkedin_profile_required_for_pairing" };
    }
    if (hasDifferentConfirmedPhone(student, phone)) {
      await client.query(
        `insert into audit_events (student_id, event_type, actor, metadata)
         values ($1, 'pairing_phone_rejected', 'provider', $2)`,
        [row.student_id, { channelType, reason: "phone_already_bound" }],
      );
      await client.query("commit");
      return { ok: false, reason: "phone_already_bound" };
    }

    await client.query(
      `update pairing_sessions
          set claimed_at = now(),
              claimed_phone = $2
        where code = $1`,
      [code, phone],
    );

    // Bind phone to the student. We don't blow away an existing phone for
    // the same LinkedIn profile; a different phone is rejected above.
    await client.query(
      `update students
          set channel_type = coalesce(nullif(channel_type, ''), $2),
              channel_address = coalesce(nullif(channel_address, ''), $3),
              channel_confirmed_at = coalesce(channel_confirmed_at, now()),
              status = case when status = 'channel_confirmed' then status else 'channel_confirmed' end,
              updated_at = now()
        where id = $1`,
      [row.student_id, channelType, phone],
    );

    await client.query("commit");
    return { ok: true, studentId: row.student_id };
  } catch (err) {
    await client.query("rollback").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

/**
 * Lookup helper for the polling endpoint /onboard/status.
 *
 * @param {import('pg').Pool} pool
 * @param {string} code
 * @returns {Promise<{paired: boolean, claimedPhone?: string} | null>}
 */
export async function lookupPairingStatus(pool, code) {
  if (!pool || !code) return null;
  const { rows } = await pool.query(
    `select claimed_at, claimed_phone from pairing_sessions where code = $1 limit 1`,
    [code],
  );
  const row = rows[0];
  if (!row) return null;
  return {
    paired: Boolean(row.claimed_at),
    claimedPhone: row.claimed_phone || "",
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function randomChars(n) {
  let out = "";
  for (let i = 0; i < n; i += 1) {
    out += CODE_ALPHABET[randomInt(0, CODE_ALPHABET.length)];
  }
  return out;
}

async function assertStudentPairingEligible(pool, studentId) {
  const { rows } = await pool.query(
    `select linkedin_profile_url from students where id = $1 limit 1`,
    [studentId],
  );
  const row = rows[0];
  if (!row) throw new Error("student_not_found");
  if (!hasLinkedInProfileUrl(row.linkedin_profile_url)) {
    throw new Error("linkedin_profile_required_for_pairing");
  }
}

function hasDifferentConfirmedPhone(student, phone) {
  const existing = normalizePhone(student?.channel_address || "");
  const incoming = normalizePhone(phone);
  return Boolean(student?.channel_confirmed_at && existing && incoming && existing !== incoming);
}

function normalizePhone(value) {
  return String(value || "").replace(/[^\d+]/g, "");
}
